### ISSUE TITLE
`.getBridgedConnections()` fails to run

### ISSUE THREAD

**Issue by Pamplemousse** [gr3p1p3/transparent-proxy#39]
Code sample shown in https://github.com/gr3p1p3/transparent-proxy#getbridgedconnections fails when run:

```sh
$ cat << EOF > example.js
const ProxyServer = require('transparent-proxy');
const server = new ProxyServer();

//starting server on port 8080
server.listen(8080, '0.0.0.0', function () {
    console.log('Proxy-Server started!', server.address());
});

setInterval(function showOpenSockets() {
    const bridgedConnections = server.getBridgedConnections();
    console.log([new Date()], 'OPEN =>', Object.keys(bridgedConnections).length)
}, 2000);
EOF

$ node example.js
Proxy-Server started! { address: '0.0.0.0', family: 'IPv4', port: 8080 }
example.js:10
    const bridgedConnections = server.getBridgedConnections();
                                      ^

TypeError: server.getBridgedConnections is not a function
    at Timeout.showOpenSockets [as _onTimeout] (/home/xmaso/Workspace/e2e-security-scanner/example.js:10:39)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

Shouldn't it be [`class ProxyServer extends net.Server`](https://github.com/gr3p1p3/transparent-proxy/blob/master/ProxyServer.js#L9) (and also in the [README.md](https://github.com/gr3p1p3/transparent-proxy/blob/master/README.md?plain=1#L3))?

**Comment by gr3p1p3** [comment]
I don't understand why, I's sure that it used to work. 
Try to access directly at `server.bridgedConnections` attrivute. It should work. 

I will try to fix this issues.

**Comment by gr3p1p3** [comment]
Ok, I used a workaround to do this. But i will work on new version @1.13.3
